spring:
  application:
    name: Transaction
    datasource:
      url: jdbc:mysql://localhost:3306/TransactionDB
      username: root
      password: pass@word1
      driver-class-name: com.mysql.cj.jdbc.driver



