spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: User
  datasource:
    url: jdbc:mysql://localhost:3306/transactiondb
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082




